version: "2"
run:
  tests: false
linters:
  enable:
    - dupl
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocyclo
    - godot
    - goheader
    - misspell
    - revive
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
