run:
  timeout: 5m
  tests: false
  go: '1.19'
linters:
  enable:
    - revive # replacement for golint
    - dupl # check duplicated code
    - goconst # check strings that can turn into constants
    - gofmt # check fmt
    - goheader # Check license headers, only checks files in current year
    - goimports # check imports
    - gocyclo # check complexity
    - govet
    - gosimple
    - ineffassign
    - unused
    - staticcheck
    - typecheck
    - godot
    - misspell
    - zerologlint
    - ginkgolinter
    - gocheckcompilerdirectives