FROM golang:1.26 AS builder
WORKDIR /src
COPY . .
ENV CGO_ENABLED=0
RUN go build --tags "nogit nounpack" -o /immucore .

FROM quay.io/kairos/kairos-init:v0.16.1 AS kairos-init

FROM quay.io/kairos/hadron:v0.4.0-core-amd64-generic-v4.1.2
COPY --from=builder /immucore /usr/bin/immucore
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init /kairos-init -l debug -s init --version "v0.0.0-test"
