FROM golang:1.26 AS builder
WORKDIR /src
COPY . .
ENV CGO_ENABLED=0
RUN go build --tags "nogit nounpack" -o /immucore .

# Branch, tag or commit sha of kairos-agent to build into the image
ARG AGENT_REF=main

FROM golang:1.26 AS agent-builder
ARG AGENT_REF
ADD https://github.com/kairos-io/kairos-agent.git#${AGENT_REF} /src
WORKDIR /src
ENV CGO_ENABLED=0
RUN go build -o /kairos-agent .

FROM quay.io/kairos/kairos-init:v0.16.1 AS kairos-init

FROM quay.io/kairos/hadron:v0.4.0-core-amd64-generic-v4.1.2
COPY --from=builder /immucore /usr/bin/immucore
RUN --mount=type=bind,from=kairos-init,src=/kairos-init,dst=/kairos-init /kairos-init -l debug -s init --version "v0.0.0-test"
# Agent from main so its kairos-sdk has in-RAM BootState detection; must land
# after kairos-init so the framework-shipped agent doesn't overwrite it.
COPY --from=agent-builder /kairos-agent /usr/bin/kairos-agent
